// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestOcbc.Models;

namespace TestOcbc.Migrations
{
    [DbContext(typeof(bankContext))]
    [Migration("20201026091510_initMigration")]
    partial class initMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TestOcbc.Models.Customers", b =>
                {
                    b.Property<long>("CustomersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("CustomerName")
                        .HasColumnType("VARCHAR(40)")
                        .HasMaxLength(40);

                    b.HasKey("CustomersId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("TestOcbc.Models.MasterTransaksi", b =>
                {
                    b.Property<int>("MasterTransaksiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("TransactionCode")
                        .HasColumnType("VARCHAR(2)")
                        .HasMaxLength(2);

                    b.Property<string>("TransactionName")
                        .HasColumnType("VARCHAR(100)")
                        .HasMaxLength(100);

                    b.HasKey("MasterTransaksiId");

                    b.ToTable("MasterTransaksis");

                    b.HasData(
                        new
                        {
                            MasterTransaksiId = 1,
                            TransactionCode = "bp",
                            TransactionName = "Beli Pulsa"
                        },
                        new
                        {
                            MasterTransaksiId = 2,
                            TransactionCode = "bt",
                            TransactionName = "Beli Listrik"
                        },
                        new
                        {
                            MasterTransaksiId = 3,
                            TransactionCode = "st",
                            TransactionName = "Setor Tunai"
                        });
                });

            modelBuilder.Entity("TestOcbc.Models.Transaction", b =>
                {
                    b.Property<long>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<double>("Amount")
                        .HasColumnType("double");

                    b.Property<long>("CustomersId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("VARCHAR(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Status")
                        .HasColumnType("VARCHAR(2)")
                        .HasMaxLength(2);

                    b.Property<DateTime>("TransDate")
                        .HasColumnType("datetime");

                    b.Property<int>("point")
                        .HasColumnType("int");

                    b.HasKey("TransactionId");

                    b.HasIndex("CustomersId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("TestOcbc.Models.Transaction", b =>
                {
                    b.HasOne("TestOcbc.Models.Customers", "Customers")
                        .WithMany("Transactions")
                        .HasForeignKey("CustomersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
